export interface NoteUsage {
  note: string;
  percentage: number;
}

export const trebleNoteUsage: NoteUsage[] = [
  { note: "C4", percentage: 10 },
  { note: "D4", percentage: 9 },
  { note: "E4", percentage: 8 },
  { note: "F4", percentage: 7 },
  { note: "G4", percentage: 7 },
  { note: "A4", percentage: 6 },
  { note: "B4", percentage: 5 },
  { note: "C5", percentage: 10 },
  { note: "D5", percentage: 9 },
  { note: "E5", percentage: 8 },
  { note: "F5", percentage: 7 },
  { note: "G5", percentage: 7 },
  { note: "A5", percentage: 6 },
  { note: "B5", percentage: 5 },
  { note: "C6", percentage: 0.4 },
  { note: "D6", percentage: 0.4 },
  { note: "E6", percentage: 0.3 },
  { note: "F6", percentage: 0.3 },
  { note: "G6", percentage: 0.2 },
  { note: "A6", percentage: 0.2 },
  { note: "B6", percentage: 0.1 },
  { note: "C7", percentage: 0.1 },
  { note: "D7", percentage: 0.1 },
  { note: "E7", percentage: 0.05 },
  { note: "F7", percentage: 0.05 },
  { note: "G7", percentage: 0.05 },
  { note: "A7", percentage: 0.04 },
  { note: "B7", percentage: 0.04 },
  { note: "C8", percentage: 0.01 },
];

export const bassNoteUsage: NoteUsage[] = [
  { note: "C0", percentage: 0.01 },
  { note: "D0", percentage: 0.01 },
  { note: "E0", percentage: 0.01 },
  { note: "F0", percentage: 0.01 },
  { note: "G0", percentage: 0.01 },
  { note: "A0", percentage: 0.02 },
  { note: "B0", percentage: 0.02 },
  { note: "C1", percentage: 0.1 },
  { note: "D1", percentage: 0.1 },
  { note: "E1", percentage: 0.2 },
  { note: "F1", percentage: 0.2 },
  { note: "G1", percentage: 0.3 },
  { note: "A1", percentage: 0.3 },
  { note: "B1", percentage: 0.4 },
  { note: "C2", percentage: 7 },
  { note: "D2", percentage: 6 },
  { note: "E2", percentage: 5 },
  { note: "F2", percentage: 4 },
  { note: "G2", percentage: 4 },
  { note: "A2", percentage: 3 },
  { note: "B2", percentage: 2 },
  { note: "C3", percentage: 7 },
  { note: "D3", percentage: 6 },
  { note: "E3", percentage: 5 },
  { note: "F3", percentage: 4 },
  { note: "G3", percentage: 4 },
  { note: "A3", percentage: 3 },
  { note: "B3", percentage: 2 },
  { note: "C4", percentage: 1.5 },
  { note: "D4", percentage: 1 },
  { note: "E4", percentage: 0.5 },
  { note: "F4", percentage: 0.4 },
  { note: "G4", percentage: 0.3 },
  { note: "A4", percentage: 0.2 },
  { note: "B4", percentage: 0.1 },
];
